[package]
name = "upodesh"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trie-rs = "0.4"
louds-rs = "0.7"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
ahash = "0.8"
regex = "1"
okkhor = { version = "0.7", features = ["regex"] }
peak_alloc = "0.2"

[[bench]]
name = "suggestions"
harness = false

# [profile.release]
# debug = true
