name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test & Benchmark Suite
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run tests
        run: cargo test --verbose
      - name: Run benchmark
        run: cargo bench
      - name: Get memory usage
        run: cargo run --example alloc

  msrv:
    name: MSRV Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.63.0 # MSRV for linux distributions (>= Debian 12)
      # We can't use `cargo test` here because criterion requires a newer version of Rust (>=1.65.0)
      - run: cargo build --verbose
